version: "3.3"

services:
  ornaments-billing:
    build: .
    container_name: ornaments-billing-app
    ports:
      - "3000:3000"
    volumes:
      # Persist database data
      - ornaments_data:/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ornaments-network

volumes:
  ornaments_data:
    driver: local

networks:
  ornaments-network:
    driver: bridge
